// Shared helpers for the file download card. The inline styles below MUST stay
// identical to FileDownloadExtension.renderHTML so articles generated by the
// Booth grab page render the same as cards edited in the console editor.

export interface DownloadFile {
  url: string
  name: string
  size: number
}

export function formatFileSize(bytes: number): string {
  if (!bytes || bytes <= 0) return ''
  const units = ['B', 'KB', 'MB', 'GB']
  let value = bytes
  let i = 0
  while (value >= 1024 && i < units.length - 1) {
    value /= 1024
    i++
  }
  return `${value >= 100 || i === 0 ? Math.round(value) : value.toFixed(1)} ${units[i]}`
}

export function escapeAttr(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

export function escapeText(value: string): string {
  return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
}

// Self-contained download card: inline styles only, no script, works on any theme.
export function buildFileDownloadHtml(file: DownloadFile): string {
  const name = file.name || '下载文件'
  return (
    `<div data-type="file-download" data-url="${escapeAttr(file.url)}" data-name="${escapeAttr(name)}" data-size="${file.size || 0}" style="margin:1rem 0;">` +
    `<a href="${escapeAttr(file.url)}" download="${escapeAttr(name)}" target="_blank" rel="noopener" style="display:flex;align-items:center;gap:12px;border:1px solid #e5e7eb;border-radius:8px;padding:12px 16px;background:#f9fafb;text-decoration:none;color:inherit;">` +
    `<span style="flex:0 0 36px;width:36px;height:36px;border-radius:8px;background:#dbeafe;color:#2563eb;display:flex;align-items:center;justify-content:center;font-size:18px;line-height:1;">&#8595;</span>` +
    `<span style="flex:1;min-width:0;display:flex;flex-direction:column;gap:2px;">` +
    `<span style="font-size:14px;font-weight:600;color:#111827;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">${escapeText(name)}</span>` +
    `<span style="font-size:12px;color:#6b7280;">${escapeText(formatFileSize(file.size))}</span>` +
    `</span>` +
    `<span style="flex:0 0 auto;font-size:14px;color:#3b82f6;">下载</span>` +
    `</a></div>`
  )
}
