# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: booth-grep
spec:
  enabled: true
  requires: ">=2.25.0"
  pluginDependencies:
    ai-foundation: ">=1.0.0 & <2.0.0"
  author:
    name: bionicbeer
    website: https://github.com/bionicbeer
  logo: logo.png
  homepage: https://github.com/bionicbeer/booth-grep-plugin#readme
  repo: https://github.com/bionicbeer/booth-grep-plugin
  issues: https://github.com/bionicbeer/booth-grep-plugin/issues
  displayName: "booth-grep"
  description: "booth-grep - Halo 插件"
  settingName: booth-grep-settings
  configMapName: booth-grep-configmap
  license:
    - name: "GPL-3.0"
      url: "https://github.com/bionicbeer/booth-grep-plugin/blob/main/LICENSE"
